### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by Israrulhaq190** [HuizhouLi/Constrained-R-CNN#1]
Hi thanks for sharing the research paper. could you guys at least inform me when you will release he source code ? I am very excited.

Thanks

**Comment by HuizhouLi** [comment]
> 您好，感谢您分享研究论文。你们至少可以通知我什么时候发布他的源代码吗？我非常激动。
> 
> 谢谢

We need some time to sort out our code. The project code will be released after the paper is accepted. If all goes well, probably in March 2020.

**Comment by HuizhouLi** [comment]
> Hi thanks for sharing the research paper. could you guys at least inform me when you will release he source code ? I am very excited.
> 
> Thanks

We need some time to sort out our code. The project code will be released after the paper is accepted. If all goes well, probably in March 2020.
