### ISSUE TITLE
tf version 

### ISSUE THREAD

**Issue by adriengb** [HuizhouLi/Constrained-R-CNN#2]
Hi @HuizhouLi ,

First thx for your work! 

I'm trying to install and run your code and I have a question related to the tensorflow version you're using . In the requirements.txt you require the version **0.12.1** that is quite old now and i'm struggling to make it run. Is there any specific reason to be in this version?

Thx!

**Comment by HuizhouLi** [comment]
Thanks for your attention. We build our model on the project of [Faster R-CNN](https://github.com/endernewton/tf-faster-rcnn/tree/r0.12) and [RGB -N](https://github.com/pengzhou1108/RGB-N). At present, we have not tried other versions of TensorFlow . You can install tensorflow0.12.1 by ‘pip install tensorflow-gpu==0.12.1’. Maybe you need to change the version of Cuda to 8.0 and cudnn to 5.1.

**Comment by adriengb** [comment]
Ok thx @HuizhouLi !
