### ISSUE TITLE
ModuleNotFoundError: No module named 'tfplot'

### ISSUE THREAD

**Issue by limingcv** [HuizhouLi/Constrained-R-CNN#5]
Thanks for your contribution, when I run the command `./train_faster_rcnn.sh 0 coco res101_cbam EXP_DIR coco_flip_cbam
`, there is an error reported: `ModuleNotFoundError: No module named 'tfplot'`, I tried to install 'tfplot' with pip and conda, but failed, could you help me? Thanks again!

**Comment by HuizhouLi** [comment]
Thanks for your attention to our work, you can try to use "pip install tensorflow-plot".

**Comment by limingcv** [comment]
Thanks a lot !
